# conda env create -f environment-dev.yml
name: lcls-live-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib-base
  - pandas
  - requests
  - urllib3<2
  - pyepics
  - pyyaml
  - pytao
  #- bmad
  - openpmd-beamphysics
  
# Developer
  - pytest
  - pdf2image
  - poppler
  - jupyterlab>=3
  - ipywidgets
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - pip
  - pip:
    - mkdocstrings-python

