# conda env create -f environment.yml
name: lcls-live
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib-base
  - pandas
  - requests
  - pyepics
  - pyyaml
  - pytao
  #- bmad
  - openpmd-beamphysics  
  - ipywidgets
  - jupyterlab
  - pip
  - https://github.com/slaclab/lcls-lattice-data/releases/download/2022.9.16/lcls-lattice-data-2022.9.16-0.tar.bz2
#  - pip:
   # - git+https://github.com/slaclab/lcls-lattice-data  
#    - git+git://github.com/slaclab/lcls-lattice-data  

