# conda env create -f environment.yml
name: lcls-live-docs
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib-base
  - pandas
  - requests
  - pyepics
  - pyyaml
  - pytao
  - bmad
  - openpmd-beamphysics  
  - ipywidgets
  - jupyterlab

