

nav:
  - index.md
  - Developer: 
    - developer/index.md
    - mkdocs: developer/mkdocs.md
  
  - other/index.md
  
  
  
site_name: LCLS-Live

theme:
  name: 'material'
  
  
markdown_extensions:
  - codehilite  
  
plugins:
    - search
    - minify