

nav:
  - index.md
  - Overview:
    - overview/index.md
  
  - Developer: 
    - developer/index.md
    - Procedures: developer/procedures.md
    - mkdocs: developer/mkdocs.md
    - Roadmap: developer/roadmap.md    
  
  - Bmad:
    - Overview: bmad/index.md
  
  - other/index.md
  
  
  
site_name: LCLS-Live

theme:
  name: 'material'
  
  
markdown_extensions:
  - codehilite  
  
plugins:
    - search
    - minify